instance_name  = "fslive"
machine_type   = "e2-medium"
zone           = "us-central1-a"
image_name     = "debian-cloud/debian-11"
public_ip_name = "fslive-public"
region         = "us-central1"
project        = "nifty-quanta-387606"
